steps:
  - name: gcr.io/$PROJECT_ID/testrunner
    args:
      - '-c'
      - |
        gcloud --version
        make --version
        pip --version
        python --version
        pytest --version
        poetry --version
    id: Verify Base Tooling Versions
    entrypoint: bash
#  - name: gcr.io/$PROJECT_ID/testrunner
#    args:
#      - '-c'
#      - |
#        set -e
#        gsutil cp $_SIC_INDEX_FILE src/sic_classification_vector_store/data/sic_index/

#        poetry install
#        make all-tests
#    id: Run Unit Tests
#    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_GAR_SOC_VECTOR_STORE_IMAGE:$SHORT_SHA
      - .
    id: Build SOC Vector Store Docker Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_GAR_SOC_VECTOR_STORE_IMAGE:$SHORT_SHA
    id: Package SOC Vector Store Docker Image In GAR
#  - name: gcr.io/$PROJECT_ID/testrunner
#    args:
#      - '-c'
#      - >
#        gcloud run deploy sic-classification-vector-store
#        --image=$_GAR_SIC_VECTOR_STORE_IMAGE:$SHORT_SHA --region europe-west2 --project
#        $_TARGET_PROJECT_ID --no-allow-unauthenticated
#    id: Deploy SIC Vector Store API
#    entrypoint: bash
#  - name: gcr.io/$PROJECT_ID/testrunner
#    args:
#      - '-c'
#      - >
#        export SIC_VECTOR_STORE_URL=$_SIC_VECTOR_STORE_URL/v1/sic-vector-store export
#        SA_ID_TOKEN=`gcloud auth print-identity-token
#        --impersonate-service-account=$_API_SA`

#        echo Waiting 5 minutes to allow API to get ready...

#        sleep 300

#        pytest cicd
#    id: Run SIC Vector Store API Smoke Tests
#    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY
