---
    name: CI
    
    on: # yamllint disable-line rule:truthy
      push:
        branches: [main]
      pull_request:
        branches: [main]
    
    concurrency:
      group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
      cancel-in-progress: true

    jobs:
        lint-test:
            name: Lint and Test
            runs-on: ubuntu-22.04
            strategy:
              matrix:
                python-version: ["3.12"]

            steps:
                - uses: actions/checkout@v4

                - name: Set up Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: ${{ matrix.python-version }}

                - name: Set PYTHONPATH
                  run: echo "PYTHONPATH=src" >> $GITHUB_ENV

                - name: Install pipx
                  run: python -m pip install --upgrade pipx

                - name: Install Poetry
                  run: pipx install poetry==2.1.1
                
                - name: Add pipx to PATH
                  run: |
                    echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH

                - name: Debug Poetry
                  run: |
                    echo "Poetry version: $(poetry --version)"]
                    echo "Poetry check: $(poetry check)"
                    echo "Poetry config: $(poetry config --list)"
  
                - name: Display Python version
                  run: python -c "import sys; print(sys.version)"

                #- name: Install dependencies
                #  run: make install-dev

                #- name: Lint Python
                #  run: make check-python-nofix

                #- name: Test Python
                #  run: make all-tests

                - name: Cleanup residue file
                  run: make clean
    
    